In [1]:
! pip install numpy

Requirement already satisfied: numpy in c:\users\ashle\anaconda3\lib\site-packages (1.18.5)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import csv

In [3]:
data =pd.read_csv(r"C:\Users\ashle\Documents\house prediction\data\sample_submission.csv")
data.head()

     Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977

In [6]:
testdataset =pd.read_csv(r"C:\Users\ashle\Documents\house prediction\data\test.csv")
data1

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [7]:
dataset =pd.read_csv(r"C:\Users\ashle\Documents\house prediction\data\train.csv")
data2.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [14]:
# Here we will check the percentage of nan values present in each feature
#1- step make the list of features which has missing values

feature_nan =[feature for feature in dataset.columns if dataset[feature].isnull().sum()>1 and dataset[feature].dtypes=='O']

for feature in feature_nan:
    print("{}:{}% missing values".format(feature,np.round(dataset[feature].isnull().mean(),4)))

Alley:0.9377% missing values
MasVnrType:0.0055% missing values
BsmtQual:0.0253% missing values
BsmtCond:0.0253% missing values
BsmtExposure:0.026% missing values
BsmtFinType1:0.0253% missing values
BsmtFinType2:0.026% missing values
FireplaceQu:0.4726% missing values
GarageType:0.0555% missing values
GarageFinish:0.0555% missing values
GarageQual:0.0555% missing values
GarageCond:0.0555% missing values
PoolQC:0.9952% missing values
Fence:0.8075% missing values
MiscFeature:0.963% missing values

### replace missing values with a new label

In [17]:
def replace_cat_feature(dataset,feature_nan):
    data=dataset.copy()
    data[feature_nan]=data[feature_nan].fillna('missing')
    return data

dataset=replace_cat_feature(dataset,feature_nan)

dataset[feature_nan].isnull().sum()

Alley           0
MasVnrType      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
PoolQC          0
Fence           0
MiscFeature     0
dtype: int64

In [18]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,missing,Reg,Lvl,AllPub,...,0,missing,missing,missing,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,missing,Reg,Lvl,AllPub,...,0,missing,missing,missing,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,missing,IR1,Lvl,AllPub,...,0,missing,missing,missing,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,missing,IR1,Lvl,AllPub,...,0,missing,missing,missing,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,missing,IR1,Lvl,AllPub,...,0,missing,missing,missing,0,12,2008,WD,Normal,250000

### search the numarical nan value

In [19]:
numarical_with_nan =[feature for feature in dataset.columns if dataset[feature].isnull().sum()>1 and dataset[feature].dtypes!='O']

for feature in numarical_with_nan:
    print("{}:{}% missing values".format(feature,np.round(dataset[feature].isnull().mean(),4)))

LotFrontage:0.1774% missing values
MasVnrArea:0.0055% missing values
GarageYrBlt:0.0555% missing values

### replacing the numarical vvalues

In [20]:
for feature in numarical_with_nan:
    ## we will replace by using median since there are outliers
    median_value=dataset[feature].median()
    
    ## create a new feature to capture nan values
    dataset[feature+'nan']=np.where(dataset[feature].isnull(),1,0)
    dataset[feature].fillna(median_value,inplace=True)
    
dataset[numarical_with_nan].isnull().sum()

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [22]:
dataset.head(50)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,65.0,8450,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,250000,0,0,0
5,6,50,RL,85.0,14115,Pave,missing,IR1,Lvl,AllPub,...,Shed,700,10,2009,WD,Normal,143000,0,0,0
6,7,20,RL,75.0,10084,Pave,missing,Reg,Lvl,AllPub,...,missing,0,8,2007,WD,Normal,307000,0,0,0
7,8,60,RL,69.0,10382,Pave,missing,IR1,Lvl,AllPub,...,Shed,350,11,2009,WD,Normal,200000,1,0,0
8,9,50,RM,51.0,6120,Pave,missing,Reg,Lvl,AllPub,...,missing,0,4,2008,WD,Abnorml,129900,0,0,0
9,10,190,RL,50.0,7420,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2008,WD,Normal,118000,0,0,0
10,11,20,RL,70.0,11200,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,129500,0,0,0
11,12,60,RL,85.0,11924,Pave,missing,IR1,Lvl,AllPub,...,missing,0,7,2006,New,Partial,345000,0,0,0
12,13,20,RL,69.0,12968,Pave,missing,IR2,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,144000,1,0,0
13,14,20,RL,91.0,10652,Pave,missing,IR1,Lvl,AllPub,...,missing,0,8,2007,New,Partial,279500,0,0,0
14,15,20,RL,69.0,10920,Pave,missing,IR1,Lvl,AllPub,...,missing,0,5,2008,WD,Normal,157000,1,0,0
15,16,45,RM,51.0,6120,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2007,WD,Normal,132000,0,0,0
16,17,20,RL,69.0,11241,Pave,missing,IR1,Lvl,AllPub,...,Shed,700,3,2010,WD,Normal,149000,1,0,0
17,18,90,RL,72.0,10791,Pave,missing,Reg,Lvl,AllPub,...,Shed,500,10,2006,WD,Normal,90000,0,0,0
18,19,20,RL,66.0,13695,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2008,WD,Normal,159000,0,0,0
19,20,20,RL,70.0,7560,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2009,COD,Abnorml,139000,0,0,0
20,21,60,RL,101.0,14215,Pave,missing,IR1,Lvl,AllPub,...,missing,0,11,2006,New,Partial,325300,0,0,0
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,missing,0,6,2007,WD,Normal,139400,0,0,0
22,23,20,RL,75.0,9742,Pave,missing,Reg,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,230000,0,0,0
23,24,120,RM,44.0,4224,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2007,WD,Normal,129900,0,0,0
24,25,20,RL,69.0,8246,Pave,missing,IR1,Lvl,AllPub,...,missing,0,5,2010,WD,Normal,154000,1,0,0
25,26,20,RL,110.0,14230,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2009,WD,Normal,256300,0,0,0
26,27,20,RL,60.0,7200,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2010,WD,Normal,134800,0,0,0
27,28,20,RL,98.0,11478,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2010,WD,Normal,306000,0,0,0
28,29,20,RL,47.0,16321,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2006,WD,Normal,207500,0,0,0
29,30,30,RM,60.0,6324,Pave,missing,IR1,Lvl,AllPub,...,missing,0,5,2008,WD,Normal,68500,0,0,0
30,31,70,C (all),50.0,8500,Pave,Pave,Reg,Lvl,AllPub,...,missing,0,7,2008,WD,Normal,40000,0,0,0
31,32,20,RL,69.0,8544,Pave,missing,IR1,Lvl,AllPub,...,missing,0,6,2008,WD,Normal,149350,1,0,0
32,33,20,RL,85.0,11049,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2008,WD,Normal,179900,0,0,0
33,34,20,RL,70.0,10552,Pave,missing,IR1,Lvl,AllPub,...,missing,0,4,2010,WD,Normal,165500,0,0,0
34,35,120,RL,60.0,7313,Pave,missing,Reg,Lvl,AllPub,...,missing,0,8,2007,WD,Normal,277500,0,0,0
35,36,60,RL,108.0,13418,Pave,missing,Reg,Lvl,AllPub,...,missing,0,9,2006,WD,Normal,309000,0,0,0
36,37,20,RL,112.0,10859,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2009,WD,Normal,145000,0,0,0
37,38,20,RL,74.0,8532,Pave,missing,Reg,Lvl,AllPub,...,missing,0,10,2009,WD,Normal,153000,0,0,0
38,39,20,RL,68.0,7922,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2010,WD,Abnorml,109000,0,0,0
39,40,90,RL,65.0,6040,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2008,WD,AdjLand,82000,0,0,1
40,41,20,RL,84.0,8658,Pave,missing,Reg,Lvl,AllPub,...,missing,0,12,2006,WD,Abnorml,160000,0,0,0
41,42,20,RL,115.0,16905,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2007,WD,Normal,170000,0,0,0
42,43,85,RL,69.0,9180,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2007,WD,Normal,144000,1,0,0
43,44,20,RL,69.0,9200,Pave,missing,IR1,Lvl,AllPub,...,missing,0,7,2008,WD,Normal,130250,1,0,0
44,45,20,RL,70.0,7945,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2006,WD,Normal,141000,0,0,0
45,46,120,RL,61.0,7658,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2010,WD,Normal,319900,0,0,0
46,47,50,RL,48.0,12822,Pave,missing,IR1,Lvl,AllPub,...,missing,0,8,2009,WD,Abnorml,239686,0,0,0
47,48,20,FV,84.0,11096,Pave,missing,Reg,Lvl,AllPub,...,missing,0,7,2007,WD,Normal,249700,0,0,0
48,49,190,RM,33.0,4456,Pave,missing,Reg,Lvl,AllPub,...,missing,0,6,2009,New,Partial,113000,0,0,1
49,50,20,RL,66.0,7742,Pave,missing,Reg,Lvl,AllPub,...,missing,0,1,2007,WD,Normal,127000,0,0,0

### Temporal variables (Date Time Variables)

In [25]:
for feature in ['YearBuilt','YearRemodAdd','GarageYrBlt']:
    dataset[feature]=dataset['YrSold']-dataset[feature]

In [26]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,65.0,8450,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,250000,0,0,0

In [27]:
dataset[['YearBuilt','YearRemodAdd','GarageYrBlt']].head()

   YearBuilt  YearRemodAdd  GarageYrBlt
0          5             5          5.0
1         31            31         31.0
2          7             6          7.0
3         91            36          8.0
4          8             8          8.0

In [38]:
##numarical value outliers are consider for this process 

## convert skew distribution into log normal distribution

import numpy as np
num_features=['LotFrontage','LotArea','1stFlrSF','GrLivArea','SalePrice']

for feature in num_features:
    dataset[feature]=np.log(dataset[feature])

In [39]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,4.174387,9.041922,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,12.429216,0,0,0

### handling Rare Categorical Feature

we will remove categorial variable that are present less than 1% of the observations

In [41]:
categorial_features=[feature for feature in dataset.columns if dataset[feature].dtype=='O']

In [42]:
categorial_features

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [43]:
for feature in categorial_features:
    temp=dataset.groupby(feature)['SalePrice'].count()/len(dataset)
    temp_df=temp[temp>0.01].index
    dataset[feature]=np.where(dataset[feature].isin(temp_df),dataset[feature],'Rare_var')

In [68]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,4.174387,9.041922,Pave,missing,Reg,Lvl,AllPub,...,missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,missing,Reg,Lvl,AllPub,...,missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,missing,IR1,Lvl,AllPub,...,missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,missing,IR1,Lvl,AllPub,...,missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,missing,IR1,Lvl,AllPub,...,missing,0,12,2008,WD,Normal,12.429216,0,0,0

In [70]:
for feature in categorial_features:
    labels_ordered=dataset.groupby([feature])['SalePrice'].mean().sort_values().index
    labels_ordered={k:i for i,k in enumerate(labels_ordered,0)}
    dataset[feature]=dataset[feature].map(labels_ordered)

In [71]:
dataset.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,3,4.174387,9.041922,1,2,0,1,1,...,2,0,2,2008,2,3,12.247694,0,0,0
1,2,20,3,4.382027,9.169518,1,2,0,1,1,...,2,0,5,2007,2,3,12.109011,0,0,0
2,3,60,3,4.219508,9.328123,1,2,1,1,1,...,2,0,9,2008,2,3,12.317167,0,0,0
3,4,70,3,4.094345,9.164296,1,2,1,1,1,...,2,0,2,2006,2,0,11.849398,0,0,0
4,5,60,3,4.430817,9.565214,1,2,1,1,1,...,2,0,12,2008,2,3,12.429216,0,0,0
5,6,50,3,4.442651,9.554993,1,2,1,1,1,...,1,700,10,2009,2,3,11.870600,0,0,0
6,7,20,3,4.317488,9.218705,1,2,0,1,1,...,2,0,8,2007,2,3,12.634603,0,0,0
7,8,60,3,4.234107,9.247829,1,2,1,1,1,...,1,350,11,2009,2,3,12.206073,1,0,0
8,9,50,1,3.931826,8.719317,1,2,0,1,1,...,2,0,4,2008,2,0,11.774520,0,0,0
9,10,190,3,3.912023,8.911934,1,2,0,1,1,...,2,0,1,2008,2,3,11.678440,0,0,0

In [75]:
scaling_feature=[feature for feature in dataset.columns if feature not in ['Id','SalePerice'] ]
len(scaling_feature)

83

In [76]:
scaling_feature

['MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleType',
 'SaleCondition',
 'SalePrice',
 'LotFrontagenan',
 'MasVnrAreanan',
 'GarageYrBltnan']

### feature scalling

In [77]:
feature_scale=[feature for feature in dataset.columns if feature not in ['Id','SalePrice']]

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(dataset[feature_scale])

MinMaxScaler()

In [80]:
scaler.transform(dataset[feature_scale])

array([[0.23529412, 0.75      , 0.41820812, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.49506375, ..., 0.        , 0.        ,
        0.        ],
       [0.23529412, 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.29411765, 0.75      , 0.42385922, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.47117546, ..., 0.        , 0.        ,
        0.        ]])

In [82]:
# transform the train and test set, and add on the Id and SalePrice variables
data = pd.concat([dataset[['Id', 'SalePrice']].reset_index(drop=True),
                    pd.DataFrame(scaler.transform(dataset[feature_scale]), columns=feature_scale)],
                    axis=1)

In [83]:
data.to_csv('X_train.csv',index=False)